export interface Bank {
  id: string;
  code: string;
  name: string;
  fullName: string;
}

export const BANKS: Bank[] = [
  {
    id: "ABB",
    code: "970425",
    name: "ABB",
    fullName: "Ngân hàng TMCP An Bình",
  },
  { id: "ACB", code: "970416", name: "ACB", fullName: "Ngân hàng TMCP Á Châu" },
  { id: "BAB", code: "970409", name: "BAB", fullName: "Ngân hàng TMCP Bắc Á" },
  {
    id: "BIDV",
    code: "970418",
    name: "BIDV",
    fullName: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
  },
  {
    id: "BVB",
    code: "970438",
    name: "BVB",
    fullName: "Ngân hàng TMCP Bảo Việt",
  },
  {
    id: "CAKE",
    code: "546034",
    name: "CAKE",
    fullName: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank",
  },
  {
    id: "CBB",
    code: "970444",
    name: "CBB",
    fullName: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam",
  },
  {
    id: "CIMB",
    code: "422589",
    name: "CIMB",
    fullName: "Ngân hàng TNHH MTV CIMB Việt Nam",
  },
  {
    id: "CITIBANK",
    code: "533948",
    name: "CITIBANK",
    fullName: "Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội",
  },
  {
    id: "COOPBANK",
    code: "970446",
    name: "COOPBANK",
    fullName: "Ngân hàng Hợp tác xã Việt Nam",
  },
  {
    id: "DBS",
    code: "796500",
    name: "DBS",
    fullName: "DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh",
  },
  { id: "DOB", code: "970406", name: "DOB", fullName: "Ngân hàng TMCP Đông Á" },
  {
    id: "EIB",
    code: "970431",
    name: "EIB",
    fullName: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
  },
  {
    id: "GPB",
    code: "970408",
    name: "GPB",
    fullName: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu",
  },
  {
    id: "HDB",
    code: "970437",
    name: "HDB",
    fullName: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
  },
  {
    id: "HLBVN",
    code: "970442",
    name: "HLBVN",
    fullName: "Ngân hàng TNHH MTV Hong Leong Việt Nam",
  },
  {
    id: "HSBC",
    code: "458761",
    name: "HSBC",
    fullName: "Ngân hàng TNHH MTV HSBC (Việt Nam)",
  },
  {
    id: "ICB",
    code: "970415",
    name: "ICB",
    fullName: "Ngân hàng TMCP Công thương Việt Nam",
  },
  {
    id: "IVB",
    code: "970434",
    name: "IVB",
    fullName: "Ngân hàng TNHH Indovina",
  },
  {
    id: "KBHCM",
    code: "970463",
    name: "KBHCM",
    fullName: "Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh",
  },
  {
    id: "KBHN",
    code: "970462",
    name: "KBHN",
    fullName: "Ngân hàng Kookmin - Chi nhánh Hà Nội",
  },
  {
    id: "KBank",
    code: "668888",
    name: "KBank",
    fullName: "Ngân hàng Đại chúng TNHH Kasikornbank",
  },
  {
    id: "KLB",
    code: "970452",
    name: "KLB",
    fullName: "Ngân hàng TMCP Kiên Long",
  },
  {
    id: "LPBANK",
    code: "970449",
    name: "LPBANK",
    fullName: "Ngân hàng TMCP Bưu điện Liên Việt",
  },
  { id: "MB", code: "970422", name: "MB", fullName: "Ngân hàng TMCP Quân đội" },
  {
    id: "MSB",
    code: "970426",
    name: "MSB",
    fullName: "Ngân hàng TMCP Hàng Hải",
  },
  { id: "NAB", code: "970428", name: "NAB", fullName: "Ngân hàng TMCP Nam Á" },
  {
    id: "NCB",
    code: "970419",
    name: "NCB",
    fullName: "Ngân hàng TMCP Quốc Dân",
  },
  {
    id: "OCB",
    code: "970448",
    name: "OCB",
    fullName: "Ngân hàng TMCP Phương Đông",
  },
  {
    id: "Oceanbank",
    code: "970414",
    name: "Oceanbank",
    fullName: "Ngân hàng Thương mại TNHH MTV Đại Dương",
  },
  {
    id: "PBVN",
    code: "970439",
    name: "PBVN",
    fullName: "Ngân hàng TNHH MTV Public Việt Nam",
  },
  {
    id: "PGB",
    code: "970430",
    name: "PGB",
    fullName: "Ngân hàng TMCP Xăng dầu Petrolimex",
  },
  {
    id: "PVCB",
    code: "970412",
    name: "PVCB",
    fullName: "Ngân hàng TMCP Đại Chúng Việt Nam",
  },
  {
    id: "SCB",
    code: "970429",
    name: "SCB",
    fullName: "Ngân hàng TMCP Sài Gòn",
  },
  {
    id: "SCVN",
    code: "970410",
    name: "SCVN",
    fullName: "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam",
  },
  {
    id: "SEAB",
    code: "970440",
    name: "SEAB",
    fullName: "Ngân hàng TMCP Đông Nam Á",
  },
  {
    id: "SGICB",
    code: "970400",
    name: "SGICB",
    fullName: "Ngân hàng TMCP Sài Gòn Công Thương",
  },
  {
    id: "SHB",
    code: "970443",
    name: "SHB",
    fullName: "Ngân hàng TMCP Sài Gòn - Hà Nội",
  },
  {
    id: "SHBVN",
    code: "970424",
    name: "SHBVN",
    fullName: "Ngân hàng TNHH MTV Shinhan Việt Nam",
  },
  {
    id: "STB",
    code: "970403",
    name: "STB",
    fullName: "Ngân hàng TMCP Sài Gòn Thương Tín",
  },
  {
    id: "TCB",
    code: "970407",
    name: "TCB",
    fullName: "Ngân hàng TMCP Kỹ thương Việt Nam",
  },
  {
    id: "TIMO",
    code: "963388",
    name: "TIMO",
    fullName: "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)",
  },
  {
    id: "TPB",
    code: "970423",
    name: "TPB",
    fullName: "Ngân hàng TMCP Tiên Phong",
  },
  {
    id: "UOB",
    code: "970458",
    name: "UOB",
    fullName: "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh",
  },
  {
    id: "Ubank",
    code: "546035",
    name: "Ubank",
    fullName: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank",
  },
  { id: "VAB", code: "970427", name: "VAB", fullName: "Ngân hàng TMCP Việt Á" },
  {
    id: "VBA",
    code: "970405",
    name: "VBA",
    fullName: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
  },
  {
    id: "VBSP",
    code: "999888",
    name: "VBSP",
    fullName: "Ngân hàng Chính sách Xã hội",
  },
  {
    id: "VCB",
    code: "970436",
    name: "VCB",
    fullName: "Ngân hàng TMCP Ngoại Thương Việt Nam",
  },
  {
    id: "VCCB",
    code: "970454",
    name: "VCCB",
    fullName: "Ngân hàng TMCP Bản Việt",
  },
  {
    id: "VIB",
    code: "970441",
    name: "VIB",
    fullName: "Ngân hàng TMCP Quốc tế Việt Nam",
  },
  {
    id: "VIETBANK",
    code: "970433",
    name: "VIETBANK",
    fullName: "Ngân hàng TMCP Việt Nam Thương Tín",
  },
  {
    id: "VPB",
    code: "970432",
    name: "VPB",
    fullName: "Ngân hàng TMCP Việt Nam Thịnh Vượng",
  },
  {
    id: "VRB",
    code: "970421",
    name: "VRB",
    fullName: "Ngân hàng Liên doanh Việt - Nga",
  },
  { id: "MOMO", code: "momo", name: "MOMO", fullName: "Ví điện tử MoMo" },
  {
    id: "VIETTELMONEY",
    code: "971005",
    name: "VIETTELMONEY",
    fullName:
      "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội",
  },
  {
    id: "VNPTMONEY",
    code: "971011",
    name: "VNPTMONEY",
    fullName:
      "Trung tâm dịch vụ tài chính số VNPT- Chi nhánh Tổng công ty truyền thông (VNPT Fintech)",
  },
];
